name: 'Get & Cache Dependencies'
description: 'Get dependencies (via npm) and cache them.'
inputs:
  caching:
    decription: 'Turn on/off dependencies caching'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Show if cache was used.'
    value: ${{ steps.install-dep }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install-dep
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "cache='${{ inputs.caching }}'" >> $GITHUB_OUTPUT
      shell: bash
